### ISSUE TITLE
AccessViolationException

### ISSUE THREAD

**Issue by mmgagnon** [51Degrees/device-detection-dotnet#5] opened 2021-05-04 17:04 UTC
I have attached a sample project that crashes with "AccessViolationException: Attempting to read or write protected memory".

![image](https://user-images.githubusercontent.com/32393262/117041608-09f71300-acd9-11eb-98cf-355e70f8c4a0.png)

Please see the attached project for the test case to reproduce the issue. Please note that there are two constants that need to be set the at top of file "DeviceInfoDetection" before this sample can be run (the path to "Enterprise-HashV41.hash" and the License Key).

[51degrees_tester_crash.zip](https://github.com/51Degrees/device-detection-dotnet/files/6422726/51degrees_tester_crash.zip)

I was not sure where to file this issue since my test case is written in C#, bu the actual issue is likely in underlying C code. Apologies if I am at the wrong place.

**Comment by mmgagnon** [comment] 2021-05-04 17:09
Some additional information :
![image](https://user-images.githubusercontent.com/32393262/117042381-e6809800-acd9-11eb-9f97-454743859a8e.png)

**Comment by ukali53** [comment] 2021-05-04 18:34
Hello @mmgagnon, could you please contact support@51degrees.com so we can discuss the issue that's been raised regarding the AccessViolationException?

**Comment by Piotr-51Degrees** [comment] 2021-05-11 15:46
Hi @mmgagnon, 

Thank you for your report and sorry for our slow response. 

Thank you for the test project - could you please provide us with a bit more information:
- What platform are you building against (32/64 bit)
- What MSVS version are you using?
- How long does it take to crash when using the test program you provided?

Many thanks and sorry again for late reply,

Thanks,
Piotr

**Comment by mmgagnon** [comment] 2021-05-11 15:50
Hi,

my computer is 64-bits, but my build target is "Any CPU". Switching to an explicit 64-bits target also reproduces the issue.

I am using Visual Studio Version 16.9.2

The time it takes to crash varies, but is usually under 10 seconds

**Comment by Piotr-51Degrees** [comment] 2021-05-11 15:57
@mmgagnon Thanks for prompt reply - I will pick up from here and will keep you updated through this thread. I can confirm that we can reproduce the problem even with the latest version of our APIs packages. We will have to schedule engineering time to have a look into this problem and I will let you know as soon as we find what the root of the problem is.

**Comment by tungntpham** [comment] 2021-05-12 09:22
Hi @mmgagnon,

Thanks for your patience. I have looked at the project and identified the potential cause of the problem. I can see that the program is spawning 100 threads, but when building the pipeline for our DeviceDetection engine the maximum concurrency is not set. The, the engine only allocates the default number of file handles which is 10. Since 10 file handles aren't enough to serve all 100 threads, it will result in an exception.
To solve this problem, you can set the concurrency to the number of threads being spawn which is 100 by using the SetConcurrency() method of the DeviceDetectionPipelineBuilder, like below:

pipeline = new DeviceDetectionPipelineBuilder()
		.UseOnPremise(FiftyOneDegrees_File_Path, FiftyOneDegrees_LicenseKey, true)
		.SetPerformanceProfile(PerformanceProfiles.LowMemory)
		.SetAutoUpdate(false)
		.SetDataFileSystemWatcher(false)
		.SetDataUpdateOnStartUp(false)
		`.SetConcurrency(100)`
		.Build();

However, for the best performance, we would advise that you should only use the maximum number of threads that matches the number of cores that your machine have. Using more than this can downgrade the performance due to context switching and time waiting per thread.

Please let us know if that resolves the issue that you are having.

Kind Regards,
Tung

**Comment by mmgagnon** [comment] 2021-05-12 12:07
@tungntpham Hi, indeed I had figured as much. However, we still wished 51degrees would handle this cleanly, rather than produce an access violation which may indicate memory corruption

**Comment by Piotr-51Degrees** [comment] 2021-05-13 06:46
Hi @mmgagnon, 

Thanks for your input and suggestions. We are intending to wrap access violation messages in the calling languages (like C#) to provide information on the likely cause of the Access Violation. 

We are focused on performance and will also assess the impact of adding a check to the C code to determine if resource pools set by the concurrent parameter have been exhausted and either throwing any exception if they have been, or having the calling thread wait on a mutex. Given the number of times the pools are accessed such checks and handling might present a performance overhead for some use cases around use in network devices.

I am closing this issue for now, please feel free to reopen if you need any further assistance.

Thanks,
Piotr

**Comment by pjolin-di** [comment] 2021-05-13 12:51
@Piotr-51Degrees Hello Piotr, 

Since this is a show-stopper for us that prevents us from reliably deploying the tools in our application, we need a more precise indication on your intended resolution timeline for this: we are actively waiting for a fix before we can use your product. 

Please give us a timeline on the planned fix and ideally a confirmation that the fix would not be just catching an error after potential memory corruption has already occured, we could do that on our end but that woudl hardly be reliable?

**Comment by Piotr-51Degrees** [comment] 2021-05-17 17:06
Hi @pjolin-di,

Thank you for your message and I am sorry to hear that this problem is a show-stopper for you. The requirement to explicitly set the number of threads supported by pipeline builder was a design choice and as such will be difficult to change. This approach is used since initial versions of V4 product were created. 

I will reopen this case in order to keep track of the problem and I will ask our engineers to verify if the number of threads configured in the pipeline builder by default is set to the number of available cores in the operating system. As Tung explained in his message, there is no gain of running more parallel jobs than the number of available cores in the OS.

Alternatively you can use a different performance profile in order to avoid requirement of explicit setting of number of parallel jobs in the C backend. Following performance profiles should work without the need of calling `SetConcurrency()` method:
- `PerformanceProfiles.Balanced`
- `PerformanceProfiles.HighPerformance`
- `PerformanceProfiles.MaxPerformance`

Example:
```
pipeline = new DeviceDetectionPipelineBuilder()
		.UseOnPremise(FiftyOneDegrees_File_Path, FiftyOneDegrees_LicenseKey, true)
		.SetPerformanceProfile(PerformanceProfiles.HighPerformance)
		.SetAutoUpdate(false)
		.SetDataFileSystemWatcher(false)
		.SetDataUpdateOnStartUp(false)
		.Build();
```

Please let me know if using different performance profile will work for you. If not I will discuss with the team how to address this problem in `LowMemory` profile and will get back to you with a proposed solution.

Thanks,
Piotr

**Comment by mmgagnon** [comment] 2021-05-17 17:14
Hi @Piotr-51Degrees , while we understand that there is generally no gain in using large amounts of threads, we are running legacy code that predates the existance of async-await, and that legacy code does its parallelism using threads. As such, we do need thread support as long as we have legacy code.

In any case, the number of thread is not really the main point here, we are able to work with that. The concern we have, really, is that 51degrees has been shown to crash with an access violation rather than cleanly handle unexpected situations. These crashes could corrupt the memory, or take our server down. The issue here is not try about the number of threads (we can handle that), it's about preventing memory corruption and crashes

**Comment by ben51degrees** [comment] 2021-06-03 13:00
Hi @mmgagnon ,
If you go for the `PerformanceProfiles.MaxPerformance` profile, this will not be an issue. This will load all the collections into continuous memory, and therefore doesn't require locks or additional memory allocations. With this configuration, the number of threads does not matter, and you can run as many as you need to.

With the `LowMemory` profile, collection elements are loaded into memory from file as and when they are requested.
The `Balanced` profile then builds another layer on top of this by adding caching to the elements which are loaded from file. In order to make this give a decent performance increase, the caches configured for a set number of threads (this is preferable to a single cache which will spend all its time locked if there are too many threads). This is the reason that the number of threads needs to be set at startup.

I hope that makes it clear that this is a very specific case which you will not encounter if you use the `MaxPerformance` profile. I agree that a check and useful exception would be better here, although we will certainly have to do a bit of testing on the performance impact as this area of code is called extremely frequently (hence why it was left to the caller to correctly set the concurrency).

I will raise an item on our work plan to consider the performance impact and potentially make the change for a future release. For now I will assume that using the `MaxPerformance` profile is an acceptable solution for you and close this. If that's not the case, do feel free to reopen.

Thanks,
Ben.

**Closed by ben51degrees** 2021-06-03 13:00 UTC
