### ISSUE TITLE
Failed to load the Device Detection native library after updating to Version 4.4.12

### ISSUE THREAD

**Issue by valgen** [51Degrees/device-detection-dotnet#26] opened 2022-12-09 05:25 UTC
Hi,

I need to mention this issue which was closed sometimes ago: [https://github.com/51Degrees/device-detection-dotnet/issues/13#issuecomment-915759693](https://github.com/51Degrees/device-detection-dotnet/issues/13#issuecomment-915759693)
In the above issue I was forced to set my project Active Platform to "x64" to work properly.

With version 4.4.12 you have introduced a change where the Native DLLs are copied to the runtimes directory, not the root of the bin directory, and the default for AnyCPU is x64 instead of x86.

Unfortunately this change has broken my project and I started receiving "_Failed to load the Device Detection native library_" errors at runtime.

**To fix this issue I had to set my project Active Platform to "Any CPU".
Unfortunately it only works in debug mode.
When I publish and release, the native dll doesn't get copied to the root of the bin directory anymore.
Only the runtimes directory gets created and it gets ignored at runtime, causing the error mentioned before.**

FYI my project is built with .NET Framework 4.8 (not .NET Core).

**Comment by Steve51D** [comment] 2022-12-12 13:57
Hi @valgen,

We made this change (to copy the dlls to the runtimes directory) at the request of another customer in order to support a solution that picks the correct dll (x64 or x86) at runtime.

As part of that work, we tested this approach against .NET Framework as well as .NET Core and did not find any issues with it in any configuration.

I'll be running some further tests to see if I can reproduce this issue, and will update with what I find.

**Comment by UptrendsMartijnH** [comment] 2022-12-13 10:48
We had trouble with this specific behaviour in the past as well. Where x86 was selected where we needed x64. We could solve this issue with the methods described in this article: [PackageReference in project files](https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#generatepathproperty)
We used the _CopyToOutputDirectory_ property for this.  Although you need packagereferences for this to work.
A better solution might be if the property/choice was overridable though the project settings and we don't have to set the project to x64 or x86 specifically. I'm not really sure how though.

**Comment by valgen** [comment] 2022-12-13 23:36
Hi @Steve51D,

I've updated my first comment in this issue. Please let me know if you need any more details.

Thanks

**Comment by Steve51D** [comment] 2022-12-14 08:54
> We had trouble with this specific behaviour in the past as well. Where x86 was selected where we needed x64. We could solve this issue with the methods described in this article: [PackageReference in project files](https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#generatepathproperty) We used the _CopyToOutputDirectory_ property for this. Although you need packagereferences for this to work. A better solution might be if the property/choice was overridable though the project settings and we don't have to set the project to x64 or x86 specifically. I'm not really sure how though.

Thanks for this input. I'm not sure what the solution is going to look like yet, but I'll keep this in mind. I'll also make a note to ensure it is tested with package reference as well as old-style references.

> Hi @Steve51D,
> 
> I've updated my first comment in this issue. Please let me know if you need any more details.
> 
> Thanks

Thanks for the update, sorry to hear the workaround does not fully solve the problem.
I'm afraid I can't give you a timeline on getting this resolved just yet, but I can say that I don't see any obvious quick fix. We'll also be entering Christmas 'release freeze' territory soon, so I think it's unlikely to be fully resolved until the new year.

**Comment by Steve51D** [comment] 2022-12-15 11:02
We have a workaround for this issue. (Note that .NET Framework projects must not target 'AnyCPU' in order for this to work)

Add the following to the post-build step in project properties:
```
copy /Y "$(TargetDir)\runtimes\win-$(Platform)\native\FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Native.dll" "$(TargetDir)\FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Native.dll"
```

This will copy the correct dll from the runtimes folder to the bin folder. 
The `/y` parameter means that this will automatically overwrite any existing dll in the bin folder with the new one.


We'll be making a release to address this as soon as we determine a more permanent solution.

**Comment by valgen** [comment] 2022-12-15 23:22
Hi @Steve51D,

Thank you for this and I look forward to see a permanent solution.

**Comment by Steve51D** [comment] 2023-02-13 15:53
Hi, sorry for the long silence on this.

We will be releasing a fix for this on Wednesday 15th as part of version 4.4.17. From the release note:

```
The on-premise device detection NuGet package now always uses the build root for native binaries when installed in a .NET Framework project.
From version 4.4.12 to 4.4.16, the setup was to put x64 and x86 native binaries in “runtimes/win-x**/native” directories within the build root, and only use the build root when AnyCPU was selected as the platform.
The change in 4.4.17 means that a single native binary will now always be copied to the build root, based on the platform. The logic is:
-	Platform=x64 – x64 binary copied
-	Platform=x86 – x86 binary copied
-	Platform=AnyCPU – x64 binary copied
As a result of this, any workarounds applied to copy the correct file from the runtimes directory (such as https://github.com/51Degrees/device-detection-dotnet/issues/26) as a build step should be removed, as the dlls will no longer exist in these locations. A workaround of this nature is no longer required, as the correct binary is selected automatically.
If you are upgrading from a version before 4.4.12, you will not need to change anything. 
This change does not apply to dotnet core, as a different mechanism is used.
```

**Comment by valgen** [comment] 2023-02-21 06:36
Hi @Steve51D,

I've updated to v4.4.17 and now I get this error:

> Method 'Warm' in type 'FiftyOne.Pipeline.Engines.Caching.DefaultFlowCache' from assembly 'FiftyOne.Pipeline.Engines, Version=4.4.11.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

>    at FiftyOne.Pipeline.Engines.FlowElements.AspectEngineBuilderBase`2.ConfigureEngine(TEngine engine)
>    at FiftyOne.Pipeline.Engines.FlowElements.OnPremiseAspectEngineBuilderBase`2.ConfigureEngine(TEngine engine)
>    at FiftyOne.Pipeline.Engines.FlowElements.AspectEngineBuilderBase`2.BuildEngine()
>    at FiftyOne.DeviceDetection.DeviceDetectionOnPremisePipelineBuilder.ConfigureAndBuild[TBuilder,TEngine](OnPremiseDeviceDetectionEngineBuilderBase`2 builder)
>    at FiftyOne.DeviceDetection.DeviceDetectionOnPremisePipelineBuilder.Build()

I'm building with Platform=AnyCPU  and can confirm the x64 binary gets copied only in the BIN root.

Can you check this out please?

Tx

**Comment by Steve51D** [comment] 2023-02-21 08:52
Hi @valgen,

This is due to an unintentional breaking change that was introduced in FiftyOne.Caching 4.4.2.

FiftyOne.Pipeline.Engines 4.4.11 requires FiftyOne.Caching >= 4.4.1, so it doesn't report any problem if you try and use 4.4.2 (until you try and compile the code). 
If you downgrade FiftyOne.Cachine to 4.4.1, it should then work correctly.

We currently working through the best way to resolve this issue with our dependencies and prevent these types of breaking changes from being introduced.

**Comment by valgen** [comment] 2023-03-02 05:24
Hi @Steve51D,

Downgrading worked fine.

I've flagged this library (FiftyOne.Caching 4.4.2) so I won't upgrade it again until you release a new version with corrected dependencies.

Thanks

**Comment by Sara51D** [comment] 2023-03-14 05:23
Hi @valgen 
We have released the new version, could you please check and let us know if things are working correctly now,
Thanks

**Comment by valgen** [comment] 2023-03-22 04:39
Hi @Sara51D,

It's working correctly now.

Thanks

**Comment by Sara51D** [comment] 2023-03-22 05:29
Issue closed after confirmation that it has been resolved.

**Closed** 2023-03-22 05:29 UTC
