### ISSUE TITLE
Running in AWS Lambda

### ISSUE THREAD

**Issue by seruminar** [51Degrees/device-detection-dotnet#30] opened 2023-03-01 22:13 UTC
Hi, I am attempting to use `FiftyOne.DeviceDetection` version `4.4.16` in AWS Lambda, which is running .NET 6 (identifier `dotnet6`) which uses an OS called Amazon Linux 2. I do not believe it is possible to run `apt install libatomic1` in the Lambda as it's a ZIP deployment, however I have not tried a Docker deployment (a related app running in Docker works after running `apt install libatomic1`). In this environment, I get the dreaded:
```
System.DllNotFoundException: Unable to load shared library 'FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Native.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libFiftyOne.DeviceDetection.Hash.Engine.OnPremise.Native.dll: cannot open shared object file: No such file or directory
```
Could you suggest me ideas on how to proceed here?

**Comment by jwrosewell** [comment] 2023-03-06 10:07
A change to .NET which modified the exception to add more information about libatomic will be made in a future version. However this additional information about the requirement for libatomic will not change the mandatory need for libatomic.

The solution for this environment will therefore need to involve using the source code and building the assemblies yourself without the need for libatomic. This will require a good understanding of C compilation. 

The FIFTYONE_DEGREES_NO_THREADING compile time macro will need to be set to prevent libatomic being used. This will however result in a solution which is single threaded and the implications will need to be handled in the calling code. See the following [cmake](https://github.com/51Degrees/common-cxx/blob/73065349dc2b49c36f6e073562a4969bb2629cea/CMakeLists.txt#L53).

**Comment by Sara51D** [comment] 2023-03-15 04:57
Hi @seruminar ,
We have released updated versions, could you please try the version released on Friday(10th March), which contain a clearer error message and have been updated for .NET version 6, and let  us know?
Thank you

**Comment by seruminar** [comment] 2023-03-22 00:11
Hi, thank you for the feedback, I have updated to version `4.4.22` but it's about the same message:
```
System.Exception: Failed to load the Device Detection native library, common causes include: 
    - Missing dependencies:
        o On Windows, the Visual C++ runtime is not installed, see the Visual Studio download page for the latest C++ Redistributable: https://visualstudio.microsoft.com/downloads/
        o On Linux, the libatomic shared object is missing. On Debian based distributions, run ‘apt install libatomic1’; on RedHat based distributions, run ‘<yum|dnf> install libatomic’.
    - The DLL file was not copied to the output directory during build, refer to the ‘System.DllNotFoundException’ inner exception for the exact library file name.
    - The incorrect DLL was copied to the output directory, this maybe be caused by the build chain determining the incorrect platform or the incorrect platform has been specified in the build process. If using the dotnet command, see https://docs.microsoft.com/en-us/dotnet/core/rid-catalog to specify the correct runtime. If using Visual Studio, make sure the selected Platform (x86/x64) matches your environment.
    - If building for .NET Framework, the AnyCPU configuration is not supported, make sure to build for the required Platform (x86/x64).
 ---> System.TypeInitializationException: The type initializer for 'FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Native.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libFiftyOne.DeviceDetection.Hash.Engine.OnPremise.Native.dll: cannot open shared object file: No such file or directory
   at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_DeviceDetectionHashEngineModule(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE.SWIGExceptionHelper..ctor()
   at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE..cctor()
   --- End of inner exception stack trace ---
   at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE.new_ConfigHashSwig()
   at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.ConfigHashSwig..ctor()
   at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Wrappers.SwigFactory.<>c.<.ctor>b__4_7()
   at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Wrappers.SwigFactory.DllExceptionHandler[T](Func`1 action)
   --- End of inner exception stack trace ---
   at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Wrappers.SwigFactory.DllExceptionHandler[T](Func`1 action)
   at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Wrappers.SwigFactory.<>c.<.ctor>b__4_3()
   at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Wrappers.SwigFactory.CreateConfig()
   at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.FlowElements.DeviceDetectionHashEngineBuilder.get_SwigConfig()
   at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.FlowElements.DeviceDetectionHashEngineBuilder.SetPerformanceProfile(PerformanceProfiles profile)
   at FiftyOne.DeviceDetection.DeviceDetectionOnPremisePipelineBuilder.ConfigureAndBuild[TBuilder,TEngine](OnPremiseDeviceDetectionEngineBuilderBase`2 builder)
   at FiftyOne.DeviceDetection.DeviceDetectionOnPremisePipelineBuilder.Build()
   ... 
   at lambda_method2(Closure , Stream , ILambdaContext , Stream )
   at Amazon.Lambda.RuntimeSupport.Bootstrap.UserCodeLoader.Invoke(Stream lambdaData, ILambdaContext lambdaContext, Stream outStream) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/UserCodeLoader.cs:line 145
   at Amazon.Lambda.RuntimeSupport.HandlerWrapper.<>c__DisplayClass8_0.<GetHandlerWrapper>b__0(InvocationRequest invocation) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/HandlerWrapper.cs:line 55
   at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InvokeOnceAsync(CancellationToken cancellationToken) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/LambdaBootstrap.cs:line 176
```
Since rebuilding the library is a huge lift we'll probably just move away from Lambda and put this into a container

**Comment by jwrosewell** [comment] 2023-03-22 07:14
Have you resolve all the issue in the exception message?

```
System.Exception: Failed to load the Device Detection native library, common causes include: 
    - Missing dependencies:
        o On Windows, the Visual C++ runtime is not installed, see the Visual Studio download page for the latest C++ Redistributable: https://visualstudio.microsoft.com/downloads/
        o On Linux, the libatomic shared object is missing. On Debian based distributions, run ‘apt install libatomic1’; on RedHat based distributions, run ‘<yum|dnf> install libatomic’.
    - The DLL file was not copied to the output directory during build, refer to the ‘System.DllNotFoundException’ inner exception for the exact library file name.
    - The incorrect DLL was copied to the output directory, this maybe be caused by the build chain determining the incorrect platform or the incorrect platform has been specified in the build process. If using the dotnet command, see https://docs.microsoft.com/en-us/dotnet/core/rid-catalog to specify the correct runtime. If using Visual Studio, make sure the selected Platform (x86/x64) matches your environment.
    - If building for .NET Framework, the AnyCPU configuration is not supported, make sure to build for the required Platform (x86/x64).


As your in a Linux environment the dependency on Libatomic is the most common missed setup step.

**Comment by jwrosewell** [comment] 2023-03-23 09:25
Rather than use Lambda have you considered calling 51Degrees cloud service directly to avoid the complexity?

We do require Libatomic to ensure the best possible performance of parallel operations. Have you asked AWS if they have a version of Lambda that supports Libatomic?

You could raise a separate feature request to make Libatomic an optional dependency and for a separate set of native assemblies to be created which use slower mutexes. We can then assess this following input from the wider community.

**Comment by jwrosewell** [comment] 2023-03-24 10:51
Relates to a [similar issue](https://github.com/51Degrees/device-detection-java/issues/17) in Java.

**Comment by kirstin51D** [comment] 2023-04-17 14:06
Hi @seruminar, have you had a chance to look at my colleagues above response about calling the 51Degrees cloud service, or contacting AWS? Let me know if you have any issues, otherwise we will look to close this issue by the end of the week. Thanks!

**Comment by seruminar** [comment] 2023-04-18 00:37
Hi @jwrosewell  and @kirstin51D, thank you for your detailed help so far! The cloud service does not have methods to support our use case, and we have not looked into contacting AWS (they most likely would point us towards custom runtimes or attempting a container deployment). We will probably just move the code to another app and lighten the Lambda to just be an execution bridge, or possibly remove it. The catalyst of Chrome UA CH is giving us enough headaches before we come back to this piece though 😆

I do not think we need this issue open anymore!

**Closed** 2023-04-19 09:02 UTC
