### ISSUE TITLE
Performance issue in returning the response

### ISSUE THREAD

**Issue by ktcoderepo** [51Degrees/device-detection-dotnet#11] opened 2021-07-01 01:17 UTC
Hi,

I've been facing performance issues with the NuGet package. The response time takes on average over 600ms and sometimes it has even gone to more than a second. 

One of the reasons could be because the CloudRequestEngineBuilder function takes HttpClient as one of the inputs. From what I understand, HttpClient has some performance issues. You can check this [Reddit Discussion](https://www.reddit.com/r/csharp/comments/ex80tv/so_i_created_a_benchmark_to_compare_the_following/)

It would be great if the function can take other providers like RestSharp or WebRequest so consumers can use whichever providers they like.

Attached below screenshots of my tests and the code I used.

Appreciate your help on this.

![test1](https://user-images.githubusercontent.com/86752429/124050258-8f8b0b00-da5d-11eb-834f-b3b7906fdc0c.PNG)
![test2](https://user-images.githubusercontent.com/86752429/124050260-9023a180-da5d-11eb-93f0-60e0ddec52e5.PNG)
![test3](https://user-images.githubusercontent.com/86752429/124050262-90bc3800-da5d-11eb-86c8-0f945ccfa287.PNG)

[Program.txt](https://github.com/51Degrees/device-detection-dotnet/files/6744726/Program.txt)

**Comment by ben51degrees** [comment] 2021-07-02 15:19
Hi @ktcoderepo ,

I like the idea of just giving an interface which can be implemented either by `HttpClient` or any other provider. 

You may be right about `HttpClient` not being as performant as it could be. However, I think the main overhead is more likely to be the HTTP request itself. It's highly dependent on your internet connection and where you are relative to our closest cloud instance. How do these figures compare to response times if you call the cloud service directly from the same machine, with the same license and evidence?

While we do try to keep our cloud service as fast as possible, it's not something we'd recommend to someone looking for high performance. For that you will want to look at our on-premise engines. The cloud engine can be swapped out for the on-premise engine without changing how you're using the pipeline. Is there a specific reason you've gone with cloud over on-premise?

Thanks,
Ben.

**Comment by ktcoderepo** [comment] 2021-07-05 23:37
Hi @ben51degrees,

Thanks for getting back on this. Appreciate it. Thanks for the feedback on the interface. Any possibility this can be available in the near future?

I use other API service's like Google and I get the responses pretty quick. So its definitely not my internet connection. I'd like to try it by calling the cloud service directly. How can I do that? I couldn't find any documentation on that. Would be great if you could send me some info on this.

I want to use the properties like IsTV and IsSmartWatch which is not available on the on-premise engines.

Looking forward to hearing from you.

Thanks.

**Comment by ben51degrees** [comment] 2021-07-06 14:14
Hi @ktcoderepo ,
Here is the [documentation for calling the cloud service directly](https://cloud.51degrees.com/api-docs/index.html).
If you could test that and let me know how a direct call compares, that would be very helpful. The relevant endpoint would be JSON.
If we can rule that out as a cause, then we know it's the engine we'll need to look into.

The timescale for when this can be looked at somewhat depends on the results of calling directly. If that's not the cause, then this change becomes higher priority. Otherwise the priority would be to look at why the cloud response is slower for you.

Thanks,
Ben

**Comment by ktcoderepo** [comment] 2021-07-07 00:57
Hi Ben,
Thanks for sharing the document. I've tried to implement it. However, in the response I get the device as Desktop even though my user agent is for TV. I guess I'm missing something.

`var resourceKey="";
var client = new RestClient(string.Format("https://cloud.51degrees.com/api/v4/{0}.json", resourceKey));
var request = new RestRequest(Method.GET);
request.AddParameter("header.user-agent", "Mozilla/5.0 (Linux; Tizen 2.3) AppleWebKit/538.1 (KHTML, like Gecko)Version/2.3 TV Safari/538.1", ParameterType.HttpHeader);
IRestResponse response = client.Execute(request);`

**Comment by ben51degrees** [comment] 2021-07-07 07:53
Hi @ktcoderepo ,
The cloud actually deals with the evidence key prefixes itself. So a parameter with the name `user-agent` is added to evidence with the key `param.user-agent` and the User-Agent header will be added with `header.user-agent`. Parameters are prioritized over headers, so parameters are used for server side matching, and direct calls from a browser will use the client's User-Agent.

If you change `header.user-agent` to just `user-agent` you will start seeing the results you expect.

Thanks,
Ben

**Comment by ben51degrees** [comment] 2021-07-07 09:10
Just to make it clear, the line which needs to change is
`request.AddParameter("header.user-agent", yourUserAgent, ParameterType.HttpHeader);`
to
`request.AddParameter("user-agent", yourUserAgent, ParameterType.HttpHeader);`

If you could confirm that, I will close this as an issue and open a feature request for the interface change.

**Comment by Steve51D** [comment] 2021-07-07 09:10
Just to add a bit of context to Ben's response, evidence names in the pipeline have two parts, the prefix and name.
The prefix indicates the source of the evidence, for example:
- **header.*** means the evidence came from an HTTP header
- **query.*** means the evidence was 'manually' supplied. Usually from a query string parameter, HTTP form parameter or similar.

Our device detection engine will accept user-agent evidence prefixed with either header or query, but if a value is available for query.user-agent then header.user-agent will be ignored.

The cloud service will automatically assign the correct prefix to evidence that it receives, so if you send 'header.user-agent' as a query string parameter, then it will end up with the name 'query.header.user-agent', which won't be used by the device detection engine.
Using just the name 'user-agent' causes the evidence in the cloud pipeline to be named 'query.user-agent', which will override whatever the HTTP header user-agent value is, and give you the results you expect.

**Comment by ktcoderepo** [comment] 2021-07-07 09:47
Thanks @ben51degrees and @Steve51D for clarifying this. I changed the name to 'user-agent' and the response is still the same. This is the response I got. Also, attached the code which uses RestSharp to call the API.

`{
  "device": {
    "ismobile": false,
    "istablet": false,
    "istv": false,
    "issmartphone": false,
    "javascripthardwareprofile": null,
    "javascripthardwareprofilenullreason": null,
    "devicetype": "Desktop",
    "issmartwatch": false,
    "isscreenfoldable": false
  },
  "javascriptProperties": [
    "device.javascripthardwareprofile"
  ]
}`

[Program.txt](https://github.com/51Degrees/device-detection-dotnet/files/6776136/Program.txt)

**Comment by ben51degrees** [comment] 2021-07-07 09:57
Hi @ktcoderepo ,

I've just tested this in a browser and get the correct response for your User-Agent. I think the problem is the use of `ParameterType.HttpHeader`. From the [RestSharp docs](https://restsharp.dev/usage/parameters.html) this will add the parameter as a header. I would expect what is happening is that this is getting overwritten with the RestSharp User-Agent. If you use the `GetOrPost` parameter type instead, this should set it as a parameter correctly.
So your code would become:
` request.AddParameter("user-agent", yourUserAgent, ParameterType.GetOrPost);`

Let me know if that gives the correct response.

**Comment by ktcoderepo** [comment] 2021-07-07 11:39
Thanks @ben51degrees. It works for me now. I did five tests and these where the response times  776, 113, 420, 236 and 254 ms. Overall I guess its much better than using the NuGet. However, I still believe it should be less than 100ms.

**Comment by ben51degrees** [comment] 2021-07-08 10:56
Thanks for confirming.
I've opened a feature request for the interface [here](https://github.com/51Degrees/pipeline-dotnet/issues/6) as the change would actually be to the pipeline that this package depends on.
I'll mark this issue closed, and keep updates on progress in the new feature request.

Thanks,
Ben.

**Closed by ben51degrees** 2021-07-08 10:56 UTC
